server:
  port: 9100

spring:
  h2:
    console:
      enabled: true

logging:
  level:
    sql: debug
    # sql: debug == hibernate.show_sql=true
    # Spring Boot provides convenient default configurations.
    # When you set logging.level.sql to DEBUG,
    # it internally configures the logging for certain packages related to SQL, including
    # 1. org.hibernate.SQL
    # 2.org.springframework.jdbc.core.JdbcTemplate.
    # This results in Hibernate SQL statements being logged.
    org.hibernate.orm.jdbc.bind: trace
