server:
  port: 9100

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    # Spring Boot 可以根據 datasource.url 自動推斷並配置合適的驅動程序
#    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    # format SQL語法
    # properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
