spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true;
          starttls.enable: true

    sendTo: ${spring.mail.sendTo}